import 'package:sosko_app/utils/constants/app_image.dart';

final specialProduct = [
  {
    "name": "Product 10",
    "description": "Automotive",
    "price": "70",
    "image": AppImages.product10,
  },
  {
    "name": "Product 11",
    "description": "Toys",
    "price": "15",
    "image": AppImages.product11,
  },
  {
    "name": "Product 2",
    "description": "Beauty",
    "price": "30",
    "image": AppImages.product2,
  },
  {
    "name": "Product 3",
    "description": "Fashion",
    "price": "25",
    "image": AppImages.product3,
  },
  {
    "name": "Product 4",
    "description": "Health",
    "price": "15",
    "image": AppImages.product4,
  },
  {
    "name": "Product 5",
    "description": "Fitness",
    "price": "50",
    "image": AppImages.product5,
  },
  {
    "name": "Product 6",
    "description": "Gadgets",
    "price": "45",
    "image": AppImages.product6,
  },
  {
    "name": "Product 7",
    "description": "Sports",
    "price": "35",
    "image": AppImages.product7,
  },
  {
    "name": "Product 8",
    "description": "Home Decor",
    "price": "40",
    "image": AppImages.product8,
  },
  {
    "name": "Product 9",
    "description": "Books",
    "price": "10",
    "image": AppImages.product9,
  },
  {
    "name": "Product 29",
    "description": "Outdoors",
    "price": "100",
    "image": AppImages.product29,
  },
  {
    "name": "Product 30",
    "description": "Travel",
    "price": "70",
    "image": AppImages.product30,
  },
  {
    "name": "Product 12",
    "description": "Kitchen",
    "price": "30",
    "image": AppImages.product12,
  },
  {
    "name": "Product 19",
    "description": "Art",
    "price": "70",
    "image": AppImages.product19,
  },
  {
    "name": "Product 20",
    "description": "Garden",
    "price": "40",
    "image": AppImages.product20,
  },
  {
    "name": "Product 21",
    "description": "Tools",
    "price": "55",
    "image": AppImages.product21,
  },
  {
    "name": "Product 22",
    "description": "Groceries",
    "price": "20",
    "image": AppImages.product22,
  },
  {
    "name": "Product 23",
    "description": "Stationery",
    "price": "10",
    "image": AppImages.product23,
  },
  {
    "name": "Product 24",
    "description": "Office Supplies",
    "price": "35",
    "image": AppImages.product24,
  },
  {
    "name": "Product 25",
    "description": "Furniture",
    "price": "200",
    "image": AppImages.product25,
  },
  {
    "name": "Product 26",
    "description": "Lighting",
    "price": "50",
    "image": AppImages.product26,
  },
  {
    "name": "Product 27",
    "description": "Baby",
    "price": "30",
    "image": AppImages.product27,
  },
  {
    "name": "Product 28",
    "description": "Crafts",
    "price": "15",
    "image": AppImages.product28,
  },
  {
    "name": "Product 13",
    "description": "Electronics",
    "price": "80",
    "image": AppImages.product13,
  },
  {
    "name": "Product 19",
    "description": "Art",
    "price": "70",
    "image": AppImages.product19,
  },
  {
    "name": "Product 20",
    "description": "Garden",
    "price": "40",
    "image": AppImages.product20,
  },
  {
    "name": "Product 21",
    "description": "Tools",
    "price": "55",
    "image": AppImages.product21,
  },
  {
    "name": "Product 22",
    "description": "Groceries",
    "price": "20",
    "image": AppImages.product22,
  },
  {
    "name": "Product 23",
    "description": "Stationery",
    "price": "10",
    "image": AppImages.product23,
  },
  {
    "name": "Product 24",
    "description": "Office Supplies",
    "price": "35",
    "image": AppImages.product24,
  },
  {
    "name": "Product 25",
    "description": "Furniture",
    "price": "200",
    "image": AppImages.product25,
  },
  {
    "name": "Product 26",
    "description": "Lighting",
    "price": "50",
    "image": AppImages.product26,
  },
  {
    "name": "Product 27",
    "description": "Baby",
    "price": "30",
    "image": AppImages.product27,
  },
  {
    "name": "Product 28",
    "description": "Crafts",
    "price": "15",
    "image": AppImages.product28,
  },
  {
    "name": "Product 14",
    "description": "Pets",
    "price": "25",
    "image": AppImages.product14,
  },
  {
    "name": "Product 15",
    "description": "Jewelry",
    "price": "100",
    "image": AppImages.product15,
  },
  {
    "name": "Product 16",
    "description": "Music",
    "price": "20",
    "image": AppImages.product16,
  },
  {
    "name": "Product 17",
    "description": "Movies",
    "price": "25",
    "image": AppImages.product17,
  },
  {
    "name": "Product 18",
    "description": "Gaming",
    "price": "60",
    "image": AppImages.product18,
  },
  {
    "name": "Product 1",
    "description": "Technology",
    "price": "20",
    "image": AppImages.product1,
  },
  {
    "name": "Product 31",
    "description": "Luggage",
    "price": "120",
    "image": AppImages.product31,
  },
  {
    "name": "Product 32",
    "description": "Footwear",
    "price": "60",
    "image": AppImages.product32,
  },
  {
    "name": "Product 33",
    "description": "Clothing",
    "price": "80",
    "image": AppImages.product33,
  },
  {
    "name": "Product 34",
    "description": "Accessories",
    "price": "90",
    "image": AppImages.product34,
  },
  {
    "name": "Product 35",
    "description": "Beauty",
    "price": "50",
    "image": AppImages.product35,
  },
  {
    "name": "Product 36",
    "description": "Watches",
    "price": "150",
    "image": AppImages.product36,
  },
  {
    "name": "Product 37",
    "description": "Sunglasses",
    "price": "80",
    "image": AppImages.product37,
  },
  {
    "name": "Product 38",
    "description": "Bags",
    "price": "110",
    "image": AppImages.product38,
  },
];
